apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    tad.gitops.set/image: ".spec.template.spec.containers[0].image"
    tad.gitops.get/image: ".spec.template.spec.containers[0].image"
    tad.gitops.set/replicas: ".spec.replicas"
    tad.gitops.get/replicas: ".spec.replicas"
  name: go-wssqwdvy
spec:
  replicas: 1
  template:
    spec:
      containers:
        - image: quay.io/rhtap_qe/go-wssqwdvy:7acf6516e7622ee6b9039ed4f645f7fda5cb2e7c@sha256:c92f7f38773ff7f9d4e4500e846d484f33685ca02d7ce8df3422706f6274470e
          name: container-image
